Week 1: Applicant Dataset Cleaning and Exploration

Objective: To clean and explore an applicant dataset using Python Pandas.

Tools: Google Colab, Python, Pandas

Tasks:

- Create and load the applicant dataset.
- Explore the dataset and identify data quality issues.
- Handle missing values.
- Remove duplicate records.
- Standardize text values.
- Clean dates and phone numbers.
- Generate a data quality summary.
- Export the cleaned dataset to CSV.

In [1]:
import pandas as pd

names = [
    "Ali Khan", "Ahmed Raza", "Sara Ahmed", "Usman Malik",
    "Ayesha Noor", "Bilal Ahmed", "Fatima Shah", "Hassan Ali",
    "Zainab Iqbal", "Hamza Tariq"
]

domains = [
    "Web Development", "Data Science", "Cyber Security",
    "App Development", "UI/UX Design"
]

universities = [
    "ABC University", "XYZ University", "City University",
    "National University", "Tech University"
]

statuses = ["Approved", "Pending", "Under Review", "Rejected"]

data = []

for i in range(50):
    data.append({
        "Applicant Name": names[i % 10],
        "Email": f"applicant{i+1}@example.com",
        "Phone": f"0300{1000000+i}",
        "Domain Applied": domains[i % 5],
        "University": universities[i % 5],
        "Application Date": f"2026-01-{(i % 28)+1:02d}",
        "Status": statuses[i % 4]
    })

df = pd.DataFrame(data)

extra_rows = [
    ["  Bilal Ahmed ", "bilal@example.com", "0300-1234567",
     "web dev", " ABC University ", "15/01/2026", " pending "],
    ["Fatima Shah", "fatima@example.com", "0311 1234567",
     "DATA SCIENCE", None, "2026-01-16", "APPROVED"],
    ["Hassan Ali", "hassan@example.com", None,
     "cyber security", "XYZ University", "invalid-date", None],
    ["Zainab Iqbal", "zainab@example.com", "03221234567",
     "webdev", "City University", "2026-01-18", "under review"],
    ["Hamza Tariq", "hamza@example.com", "0333-1234567",
     "app development", "National University", "19/01/2026", "REJECTED"],
    [None, "missingname@example.com", "03441234567",
     "UI/UX Design", None, "2026-01-20", "pending"],
    ["Usman Malik", None, "03001234567",
     "Web Development", "Tech University", "2026-01-21", "Approved"],
    ["Ayesha Noor", "ayesha@example.com", "0311-2223333",
     "web development", "ABC University", "2026-01-22", "Pending"],
    ["Sara Ahmed", "sara@example.com", "0322 3334444",
     "Data Science", "XYZ University", "2026-01-23", "Under Review"],
    ["Ali Khan", "applicant1@example.com", "03001000000",
     "Web Development", "ABC University", "2026-01-01", "Approved"]
]

extra_df = pd.DataFrame(extra_rows, columns=df.columns)
df = pd.concat([df, extra_df], ignore_index=True)

df.to_csv("applicants.csv", index=False)

print("Dataset created successfully!")
print("Dataset shape:", df.shape)
display(df.head())

Dataset created successfully!
Dataset shape: (60, 7)

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ali Khan,applicant1@example.com,03001000000,Web Development,ABC University,2026-01-01,Approved
1,Ahmed Raza,applicant2@example.com,03001000001,Data Science,XYZ University,2026-01-02,Pending
2,Sara Ahmed,applicant3@example.com,03001000002,Cyber Security,City University,2026-01-03,Under Review
3,Usman Malik,applicant4@example.com,03001000003,App Development,National University,2026-01-04,Rejected
4,Ayesha Noor,applicant5@example.com,03001000004,UI/UX Design,Tech University,2026-01-05,Approved

In [2]:
print("Dataset Shape:", df.shape)

print("\nFirst 5 Records:")
display(df.head())

print("\nDataset Information:")
df.info()

print("\nMissing Values:")
print(df.isnull().sum())

print("\nExact Duplicate Rows:")
print(df.duplicated().sum())

Dataset Shape: (60, 7)

First 5 Records:

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ali Khan,applicant1@example.com,03001000000,Web Development,ABC University,2026-01-01,Approved
1,Ahmed Raza,applicant2@example.com,03001000001,Data Science,XYZ University,2026-01-02,Pending
2,Sara Ahmed,applicant3@example.com,03001000002,Cyber Security,City University,2026-01-03,Under Review
3,Usman Malik,applicant4@example.com,03001000003,App Development,National University,2026-01-04,Rejected
4,Ayesha Noor,applicant5@example.com,03001000004,UI/UX Design,Tech University,2026-01-05,Approved

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Applicant Name    59 non-null     object
 1   Email             59 non-null     object
 2   Phone             59 non-null     object
 3   Domain Applied    60 non-null     object
 4   University        58 non-null     object
 5   Application Date  60 non-null     object
 6   Status            59 non-null     object
dtypes: object(7)
memory usage: 3.4+ KB

Missing Values:
Applicant Name      1
Email               1
Phone               1
Domain Applied      0
University          2
Application Date    0
Status              1
dtype: int64

Exact Duplicate Rows:
1

Day 1: Initial Dataset Exploration

The dataset was successfully created and loaded using Pandas. It contains 60 rows and 7 columns. Initial exploration was performed using "head()", "info()", "isnull().sum()", and "duplicated().sum()".

The dataset will be checked for missing values, duplicate records, inconsistent text formatting, and date-format issues before cleaning.

In [3]:
print("Missing values before cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
Applicant Name      1
Email               1
Phone               1
Domain Applied      0
University          2
Application Date    0
Status              1
dtype: int64

In [4]:
df = df.replace(r'^\s*$', pd.NA, regex=True)

print(df.isnull().sum())

Applicant Name      1
Email               1
Phone               1
Domain Applied      0
University          2
Application Date    0
Status              1
dtype: int64

In [5]:
# Remove rows where Applicant Name is missing
df = df.dropna(subset=["Applicant Name"])

# Fill missing values with sensible defaults
df["Email"] = df["Email"].fillna("not_provided@example.com")
df["University"] = df["University"].fillna("Not Specified")
df["Status"] = df["Status"].fillna("Under Review")

print("Missing values after cleaning:")
print(df.isnull().sum())

print("\nDataset shape after cleaning:", df.shape)

Missing values after cleaning:
Applicant Name      0
Email               0
Phone               1
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

Dataset shape after cleaning: (59, 7)

Day 2: Handling Missing Values

Missing values were identified using Pandas. Blank or whitespace-only cells were converted to missing values.

Rows with missing Applicant Name were removed because the applicant could not be reliably identified. Missing Email values were filled with a placeholder, while missing University values were replaced with "Not Specified". Missing Status values were set to "Under Review" because the application status was not recorded.

The missing-value counts were checked again after cleaning to verify the results.

In [6]:
print(df.isnull().sum())

Applicant Name      0
Email               0
Phone               1
Domain Applied      0
University          0
Application Date    0
Status              0
dtype: int64

In [7]:
print("Exact duplicate rows:", df.duplicated().sum())

print("Duplicate emails:", df.duplicated(subset=["Email"]).sum())

Exact duplicate rows: 1
Duplicate emails: 1

In [8]:
# Check exact duplicate rows
print("Exact duplicates before cleaning:", df.duplicated().sum())

# Remove exact duplicate rows
df = df.drop_duplicates()

print("Exact duplicates after cleaning:", df.duplicated().sum())
print("Dataset shape:", df.shape)

Exact duplicates before cleaning: 1
Exact duplicates after cleaning: 0
Dataset shape: (58, 7)

In [9]:
print("Duplicate emails:", df.duplicated(subset=["Email"]).sum())

# Show rows with duplicate emails
display(df[df.duplicated(subset=["Email"], keep=False)])

Duplicate emails: 0

Empty DataFrame
Columns: [Applicant Name, Email, Phone, Domain Applied, University, Application Date, Status]
Index: []

In [10]:
df = df.drop_duplicates(subset=["Email"], keep="first")

print("Duplicate emails after cleaning:",
      df.duplicated(subset=["Email"]).sum())

print("Final dataset shape:", df.shape)

Duplicate emails after cleaning: 0
Final dataset shape: (58, 7)

In [11]:
print("Exact duplicate rows:", df.duplicated().sum())
print("Duplicate emails:", df.duplicated(subset=["Email"]).sum())
print("Dataset shape:", df.shape)

Exact duplicate rows: 0
Duplicate emails: 0
Dataset shape: (58, 7)

### Day 3: Removing Duplicate Records

Exact duplicate rows were identified and removed using Pandas. Duplicate email addresses were also checked, and repeated applicant records were removed while keeping the first occurrence.

After cleaning, the dataset contained 58 rows and 7 columns. A final verification confirmed that no exact duplicate rows or duplicate email addresses remained.

In [12]:
print("Domain values:")
print(df["Domain Applied"].unique())

print("\nStatus values:")
print(df["Status"].unique())

print("\nUniversity values:")
print(df["University"].unique())

Domain values:
['Web Development' 'Data Science' 'Cyber Security' 'App Development'
 'UI/UX Design' 'web dev' 'DATA SCIENCE' 'cyber security' 'webdev'
 'app development' 'web development']

Status values:
['Approved' 'Pending' 'Under Review' 'Rejected' ' pending ' 'APPROVED'
 'under review' 'REJECTED']

University values:
['ABC University' 'XYZ University' 'City University' 'National University'
 'Tech University' ' ABC University ' 'Not Specified']

In [13]:
text_columns = [
    "Applicant Name",
    "Email",
    "Domain Applied",
    "University",
    "Status"
]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

print("Extra spaces removed.")

Extra spaces removed.

In [14]:
domain_mapping = {
    "web dev": "Web Development",
    "webdev": "Web Development",
    "web development": "Web Development",
    "data science": "Data Science",
    "cyber security": "Cyber Security",
    "app development": "App Development",
    "ui/ux design": "UI/UX Design"
}

df["Domain Applied"] = (
    df["Domain Applied"]
    .str.lower()
    .map(domain_mapping)
    .fillna(df["Domain Applied"])
)

In [15]:
df["Status"] = df["Status"].str.title()

df["Applicant Name"] = df["Applicant Name"].str.title()

df["Email"] = df["Email"].str.lower()

df["University"] = df["University"].str.title()

In [16]:
print("Standardized domains:")
print(df["Domain Applied"].unique())

print("\nStandardized statuses:")
print(df["Status"].unique())

print("\nStandardized universities:")
print(df["University"].unique())

Standardized domains:
['Web Development' 'Data Science' 'Cyber Security' 'App Development'
 'UI/UX Design']

Standardized statuses:
<StringArray>
['Approved', 'Pending', 'Under Review', 'Rejected']
Length: 4, dtype: string

Standardized universities:
<StringArray>
[     'Abc University',      'Xyz University',     'City University',
 'National University',     'Tech University',       'Not Specified']
Length: 6, dtype: string

Day 4: Text Standardization

Text columns were cleaned by removing leading and trailing whitespace. Domain names were standardized using a mapping dictionary to make inconsistent labels consistent. Status, applicant names, and university names were converted to title case, while email addresses were converted to lowercase.

The unique values were checked after cleaning to verify the standardization results.

In [17]:
print("Application Date data type:")
print(df["Application Date"].dtype)

print("\nSample dates:")
print(df["Application Date"].tail(10))

print("\nMissing phone numbers:")
print(df["Phone"].isnull().sum())

Application Date data type:
object

Sample dates:
48      2026-01-21
49      2026-01-22
50      15/01/2026
51      2026-01-16
52    invalid-date
53      2026-01-18
54      19/01/2026
56      2026-01-21
57      2026-01-22
58      2026-01-23
Name: Application Date, dtype: object

Missing phone numbers:
1

In [18]:
df["Application Date"] = pd.to_datetime(
    df["Application Date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

print("Date data type:", df["Application Date"].dtype)
print("Invalid dates:", df["Application Date"].isnull().sum())

Date data type: datetime64[ns]
Invalid dates: 1

In [19]:
df["Phone"] = df["Phone"].str.replace(
    r"[\s-]", "", regex=True
)

print(df["Phone"].tail(10))
print("Missing phone numbers:", df["Phone"].isnull().sum())

48    03001000048
49    03001000049
50    03001234567
51    03111234567
52           None
53    03221234567
54    03331234567
56    03001234567
57    03112223333
58    03223334444
Name: Phone, dtype: object
Missing phone numbers: 1

In [20]:
print(df[["Application Date", "Phone"]].tail(10))
print("\nData types:")
print(df[["Application Date", "Phone"]].dtypes)

   Application Date        Phone
48       2026-01-21  03001000048
49       2026-01-22  03001000049
50       2026-01-15  03001234567
51       2026-01-16  03111234567
52              NaT         None
53       2026-01-18  03221234567
54       2026-01-19  03331234567
56       2026-01-21  03001234567
57       2026-01-22  03112223333
58       2026-01-23  03223334444

Data types:
Application Date    datetime64[ns]
Phone                       object
dtype: object

In [21]:
print("Invalid/missing dates:", df["Application Date"].isnull().sum())
print("Missing phone numbers:", df["Phone"].isnull().sum())

display(
    df[df["Application Date"].isnull()][
        ["Applicant Name", "Application Date"]
    ]
)

Invalid/missing dates: 1
Missing phone numbers: 1

   Applicant Name Application Date
52     Hassan Ali              NaT

Day 5: Data Types, Dates, and Phone Numbers

Application dates were converted to Pandas datetime format. Invalid date values were converted to missing dates using "errors="coerce"" so they could be identified for further review.

Phone numbers were standardized by removing spaces and hyphens. Missing phone numbers were preserved rather than replaced with invented values. The updated data types and cleaned values were checked after processing.

In [22]:
print("DATA QUALITY SUMMARY")
print("-" * 30)

print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nExact duplicate rows:", df.duplicated().sum())

print(
    "Duplicate emails:",
    df.duplicated(subset=["Email"]).sum()
)

print("\nUnique domains:")
print(df["Domain Applied"].nunique())

print("\nUnique statuses:")
print(df["Status"].nunique())

print("\nColumn data types:")
print(df.dtypes)

DATA QUALITY SUMMARY
------------------------------
Total rows: 58
Total columns: 7

Missing values per column:
Applicant Name      0
Email               0
Phone               1
Domain Applied      0
University          0
Application Date    1
Status              0
dtype: int64

Exact duplicate rows: 0
Duplicate emails: 0

Unique domains:
5

Unique statuses:
4

Column data types:
Applicant Name      string[python]
Email               string[python]
Phone                       object
Domain Applied              object
University          string[python]
Application Date    datetime64[ns]
Status              string[python]
dtype: object

In [23]:
print("Rows with missing dates:")
display(df[df["Application Date"].isnull()])

print("Rows with missing phone numbers:")
display(df[df["Phone"].isnull()])

Rows with missing dates:

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
52,Hassan Ali,hassan@example.com,None,Cyber Security,Xyz University,NaT,Under Review

Rows with missing phone numbers:

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
52,Hassan Ali,hassan@example.com,None,Cyber Security,Xyz University,NaT,Under Review

In [24]:
print("Total rows:", df.shape[0])
print("Total columns:", df.shape[1])

print("\nMissing values per column:")
print(df.isnull().sum())

print("\nExact duplicate rows:", df.duplicated().sum())
print("Duplicate emails:", df.duplicated(subset=["Email"]).sum())

Total rows: 58
Total columns: 7

Missing values per column:
Applicant Name      0
Email               0
Phone               1
Domain Applied      0
University          0
Application Date    1
Status              0
dtype: int64

Exact duplicate rows: 0
Duplicate emails: 0

Day 6: Data Quality Summary

The cleaned dataset contains 58 rows and 7 columns. No missing values remain in Applicant Name, Email, Domain Applied, University, or Status.

One phone number is missing, and one application date is invalid. No exact duplicate rows or duplicate email addresses remain. The dataset was reviewed to verify the results of the cleaning process before export.

In [25]:
df.to_csv("applicants_cleaned.csv", index=False)

print("Cleaned dataset exported successfully!")

Cleaned dataset exported successfully!

In [26]:
import os

print("File exists:", os.path.exists("applicants_cleaned.csv"))
print("File size:", os.path.getsize("applicants_cleaned.csv"), "bytes")

display(df.head())

File exists: True
File size: 5769 bytes

,Applicant Name,Email,Phone,Domain Applied,University,Application Date,Status
0,Ali Khan,applicant1@example.com,03001000000,Web Development,Abc University,2026-01-01,Approved
1,Ahmed Raza,applicant2@example.com,03001000001,Data Science,Xyz University,2026-01-02,Pending
2,Sara Ahmed,applicant3@example.com,03001000002,Cyber Security,City University,2026-01-03,Under Review
3,Usman Malik,applicant4@example.com,03001000003,App Development,National University,2026-01-04,Rejected
4,Ayesha Noor,applicant5@example.com,03001000004,UI/UX Design,Tech University,2026-01-05,Approved

In [27]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [28]:
df.to_csv(
    "/content/drive/MyDrive/applicants_cleaned.csv",
    index=False
)

print("CSV saved to Google Drive!")

CSV saved to Google Drive!